---
name: edge-home-orchestration-go
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install glide
        run: |
          sudo add-apt-repository -y ppa:masterminds/glide
          sudo apt-get update
          sudo apt-get install -y glide

      - name: Build the project
        run: ./build.sh
