name: PR reviewer reminder
on:
  schedule:
    # Check reviews every weekday, 10:00 and 17:00
    - cron: '0 10,17 * * 1-5'

permissions:
  contents: read

jobs:
  pull-request-reviewer-reminder: 
    runs-on: ubuntu-latest
    steps:
      - uses: tommykw/pull-request-reviewer-reminder-action@bc62999543e1220874b74e4c500a2559f5dfe42e # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required
          reminder_message: 'One business day has passed since the review started. Give priority to reviews as much as possible. ğŸ™' # Required. Messages to send to reviewers on Github.
          review_turnaround_hours: 24 # Required. This is the deadline for reviews. If this time is exceeded, a reminder wil be send.
